homework3/hdweb/urls.py
from django.conf.urls import include, url
from django.contrib.auth.models import User
from django.contrib import admin
from accounts.views import login, logout, index
from job.views import upload, display, job, execute, delete, status


urlpatterns = [
	url(r'^$',index),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^accounts/login/$',login),
	url(r'^accounts/logout/$',logout),
	url(r'^index/$',index),
	url(r'^upload/$', upload, name='upload'),
	url(r'^job/$', job),
	url(r'^execute/$', execute),
	url(r'^status/$', status),
	url(r'^delete/(?P<id>[0-9]+)/$', delete),
]

homework3/job/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('myproject.myapp.views',
    url(r'^list/$', 'list', name='list'),
)

homework3/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Userid(models.Model):
	id = models.AutoField(primary_key=True)
	user = models.ForeignKey(User, default='0')

homework3/job/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Userid


def upload_mapper(self, filename):
	#uid = Userid.objects.get(username=self.user.username)
    return '/'.join([str(self.user.id), "mapper.py"])

def upload_reducer(self, filename):
	#uid = Userid.objects.get(username=self.user.username)
    return '/'.join([str(self.user.id), "reducer.py"])
	
def upload_inputfile(self, filename):
	#uid = Userid.objects.get(username=self.user.username)
    return '/'.join([str(self.user.id), "input.txt"])

class Document(models.Model):

	id = models.AutoField(primary_key=True)
	#file1 = models.FileField(upload_to=upload_mapper, default='0')
	#file2 = models.FileField(upload_to=upload_reducer, default='0')
	#file3 = models.FileField(upload_to=upload_inputfile, default='0')
	datetime = models.DateTimeField(null=True, blank=True)
	user = models.ForeignKey(User, blank=True)
	status = models.CharField(max_length=10, null=True, blank=True)
	jobname = models.CharField(max_length=20, null=True, blank=True)

homework3/job/forms.py
# -*- coding: utf-8 -*-

from django import forms

class DocumentForm(forms.Form):
	jobname = forms.CharField(max_length=20)
	file1 = forms.CharField( widget=forms.Textarea())
	file2 = forms.CharField( widget=forms.Textarea())
	file3 = forms.CharField( widget=forms.Textarea())

homework3/accounts/views.py
from django.shortcuts import render
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

def login(request):

    if request.user.is_authenticated(): 
        return HttpResponseRedirect('/index/')
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    
    user = auth.authenticate(username=username, password=password)

    if user is not None and user.is_active:
        auth.login(request, user)
        return HttpResponseRedirect('/index/')
    else:
        return render(request,'login.html',locals()) 

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/index/')
		
def index(request):
    return render(request,'index.html',locals())

homework3/job/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect,HttpResponse, HttpResponseBadRequest
from django.core.urlresolvers import reverse
from django.utils import timezone
from job.models import Document
from job.forms import DocumentForm
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
import os
import json

def display(request):
	documents = Document.objects.all()
	return HttpResponse(documents)
	
def status(request):
	if request.method == 'GET':
		id = request.GET['id']
		#jbname = "job_"+str(request.user.id)+"_"+str(jobpk)
		uid = str(request.user.id)
		path = "media/"+uid+"/"+str(id)+"/output.txt"
		
		try:
			file = open(path,'r')
			res = file.read()
			file.close()
		except:
			res = "Can not found !"
			#res = os.popen("cat path").read()
		
		return HttpResponse(
			json.dumps({"result": res, "id" : id}),
			content_type="application/json"
		)
	else:
		return HttpResponse(
			json.dumps({"error": "not_GET"}),
			content_type="application/json"
		)
		
		
def execute(request):
	if request.method == 'GET':
	
		jobpk = request.GET['id']
		#cmd = "cp scripts/run_script.sh media/"+str(request.user.id)+"/"+str(jobpk)+"/run_script.sh"
		jbname = "job_"+str(request.user.id)+"_"+str(jobpk)
		cmd = "\
			cd media/"+str(request.user.id)+"/"+str(jobpk)+";\
			STREAMJAR=/opt/hadoop/share/hadoop/tools/lib/hadoop-streaming-2.6.0.jar;\
			INPUT=input.txt;\
			INPUT_DIR=/input;\
			OUTPUT=output.txt;\
			OUTPUT_DIR=/output;\
			MAPPER=./mapper.py;\
			REDUCER=./reducer.py;\
			hdfs dfs -rm -r -f $INPUT_DIR;\
			hdfs dfs -mkdir /input;\
			hdfs dfs -put $INPUT $INPUT_DIR;\
			hdfs dfs -rm -r -f $OUTPUT_DIR;\
			hadoop jar $STREAMJAR\
			-D mapreduce.job.name='"+jbname+"'\
			-files $MAPPER,$REDUCER -mapper $MAPPER -reducer $REDUCER\
			-input $INPUT_DIR -output $OUTPUT_DIR;\
			hdfs dfs -cat $OUTPUT_DIR/part* > $OUTPUT;\
		"
		res = os.popen(cmd).read()
		
		return HttpResponse(
			json.dumps({"result": "ok", "id" : jobpk}),
			content_type="application/json"
		)
	
	else:
		return HttpResponse(
			json.dumps({"error": "not_GET"}),
			content_type="application/json"
		)
		
@login_required
def job(request):
	r = Document.objects.order_by('-datetime')
	form = DocumentForm()
	return render(request,"job.html",locals())

def delete(request,id):

	if request.method == 'DELETE':
	
		uid = str(request.user.id)
		path = "media/"+uid+"/"+str(id)
		res = os.popen("rm -r "+path).read()
		document = Document.objects.get(id=id)
		document.delete()
		

		return HttpResponse(
			json.dumps({"result": "ok", "id" : id}),
			content_type="application/json"
		)
	else:
		return HttpResponse(
			json.dumps({"error": "not_DELETE"}),
			content_type="application/json"
		)
	
def upload(request):

    # Handle file upload
	if request.method == 'POST':

		f = DocumentForm(request.POST)
		if f.is_valid():
		
			jobname = f.cleaned_data['jobname']
			time_now = timezone.now()
			c = Document.objects.create(
					datetime = time_now,
					user = request.user,
					jobname = jobname,
					status = "NEW JOB"
				)
			id = c.id

			uid = (request.user.id)
			path = "media/"+str(uid)+"/"+str(id)
			if not os.path.exists(path):
				os.makedirs(path)
			
			file1 = f.cleaned_data['file1']
			ff = open(path+"/mapper.py",'w')  
			ff.write(file1)
			ff.close()
			
			file1 = f.cleaned_data['file2']
			ff = open(path+"/reducer.py",'w')  
			ff.write(file1)
			ff.close()
			
			file1 = f.cleaned_data['file3']
			ff = open(path+"/input.txt",'w')  
			ff.write(file1)
			ff.close()		
			
			response_data = {}
			response_data['jobname'] = c.jobname
			response_data['created_time'] = c.datetime.strftime('%b. %d, %Y %I:%M %P')
			response_data['id'] = c.id
			response_data['status'] = c.status
			
			return HttpResponse(
				json.dumps(response_data),
				content_type="application/json"
			)
		else:

			# Prepare JSON for parsing
			errors_dict = {}
			if f.errors:
				for error in f.errors:
					e = f.errors[error]
					errors_dict[error] = e
			return HttpResponseBadRequest(json.dumps(errors_dict))

	else:
		return HttpResponse(
			json.dumps({"error": "not_POST"}),
			content_type="application/json"
		)

homework3/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Hadoop web service</title>

	{% load staticfiles %}
	<!-- Bootstrap -->
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}" media="screen">
    <link rel="stylesheet" href="{% static "css/custom.min.css" %}">

</head>

<body>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="/" class="navbar-brand">Hadoop web service</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
			<ul class="nav navbar-nav">
				<li><a href="/job/">MyJob</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				{% if request.user.is_authenticated %}
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Hi, {{request.user}} <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><a href="/accounts/logout/">Logout</a></li>
						</ul>
					</li>
				{% else %}
					<li><a href="/accounts/login/">Login</a></li>
				{% endif %}
			</ul>

        </div>
      </div>
    </div>
    {% block body %}{% endblock %}
</body>


	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
	{% block scripts %}{% endblock %}
</html>

homework3/templates/index.html
{% extends 'base.html' %}
{% block body %}

	<div class="container">

      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-8 col-md-7 col-sm6">
	        
			
				{% if request.user.is_authenticated %}
					<h2>Hello, {{request.user}}</h2>
					<h2>Welcome to Hadoop web service.</h2><br>
					<a href="/job/" class="btn btn-success">Here to start</a><br><br>
					<img src='http://insidebigdata.com/wp-content/uploads/2013/10/Hadoop_elephants.jpg'>
					
				{% else %}
					<h2>Hello, Guest</h2>
					<h2>Welcome to Hadoop web service.</h2><br>
					<a href="/accounts/login/" class="btn btn-success">Login to start</a><br><br>
					<img src='http://insidebigdata.com/wp-content/uploads/2013/10/Hadoop_elephants.jpg'>
				{% endif %}
				
          </div>
    
        </div>

      </div>
	  
	</div>
	
{% endblock %}

homework3/templates/job.html
{% extends 'base.html' %}
{% block body %}

	<div class="container" >
		<div class="page-header">
		<a href="#" class="btn btn-info" id="newjob">New Job</a>
		</div>
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12">
				<div id="results"></div>
				<div id="status"></div>
				<div id="loading_msg"></div>
			</div>
		</div>
	</div>
	
	
	
	<div class="container" id= "hideform" >
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12">		
				<form action"/upload/" method="post" enctype="multipart/form-data" class="form-horizontal" id="post-form">{% csrf_token %}
					<div class="jumbotron">
					<fieldset>
						<legend>Create a new Job</legend>
						
						<div class="form-group" id="gg_name">
						  <label for="jobname" class="col-lg-2 control-label">Job name</label>
						  <div class="col-lg-10"> 
							<div id="g_name"></div>
							<input type="text" class="form-control" id="id_name" name="name"  placeholder="Job name">
						  </div>
						</div>
						
						<div class="form-group " id="gg_file1">
						  <label for="textArea" class="col-lg-2 control-label">Mapper.py</label>
						  <div class="col-lg-10 ">
							<div id="g_file1"></div>
							<textarea class="form-control" rows="3" id="id_file1"></textarea>
						  </div>
						</div>
						
						<div class="form-group" id="gg_file2">
						  <label for="textArea" class="col-lg-2 control-label">Reducer.py</label>
						  <div class="col-lg-10">
							<div id="g_file2"></div>
							<textarea class="form-control" rows="3" id="id_file2"></textarea>
						  </div>
						</div>
						
						<div class="form-group" id="gg_file3">
						  <label for="textArea" class="col-lg-2 control-label">Input file</label>
						  <div class="col-lg-10">
							<div id="g_file3"></div>
							<textarea class="form-control" rows="3" id="id_file3"></textarea>
						  </div>
						</div>
						
						<div class="form-group">
						  <div class="col-lg-10 col-lg-offset-2">
							<button type="submit" class="btn btn-default btn-primary">Submit</button>
							<button type="reset" class="btn btn-default">Reset</button>
						  </div>
						</div>
					
					</fieldset>
					</div>
				</form>
			</div>
		</div>
	</div>


	<div class="container">
        <div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12">

				<!-- List of uploaded documents -->
				<h2>My Jobs</h2>
				
				{% if r %}
				<table class="table table-striped table-hover " id="job_list">
					<thead>
					<tr class="active">
						<th>ID</th>
						<th>Job Name</th>
						<th>Created Time</th>
						<!-- <td>Status</td>-->
						<th>Execute</th>
						<th>Delete</th>
					</tr>
					</thead>
					
						{% for c in r %}
						<tbody id='job-{{c.id}}'>				
							<tr>
								<td>{{c.id}}</td>
								<td>{{c.jobname}}</td>
								<td>{{c.datetime}}</td>
								<!-- <td><span id='status-job-{{c.id}}' class="label label-primary">{{c.status}}</span></td>-->
								<td><a id='execute-job-{{c.id}}' class="btn btn-primary btn-xs btn-info">Execute</a></td>
								<td><a id='delete-job-{{c.id}}' class="btn btn-primary btn-xs btn-danger">Delete</a></td>
							</tr>
						</tbody>				
						{% endfor %}
					
					
				</table> 
				{% else %}
					<p>No files</p>
				{% endif %}
				
			</div>
        </div>
	</div>
	
{% endblock %}

{% block scripts %}
{% load staticfiles %}
<script src="{% static 'js/upload.js' %}"></script>
<script src="{% static 'js/csrf.js' %}"></script>
{% endblock %}

homework3/templates/login.html
{% extends 'base.html' %}
{% block body %}

    <div class="container">

      <div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-8 col-md-7 col-sm6">
	        <h1>Login</h1>
            <p class="lead">Please input your account and password</p>
			
			
			<form class="form-horizontal" action="" method="post"> {% csrf_token %} 
				<fieldset>
					
					<div class="form-group">
					  <label for="inputEmail" class="col-lg-2 control-label">Account</label>
					  <div class="col-lg-10">
						<input type="text" class="form-control" name="username" value="" id="username" placeholder="Account">
					  </div>
					</div>
					<div class="form-group">
					  <label for="inputPassword" class="col-lg-2 control-label">Password</label>
					  <div class="col-lg-10">
						<input type="password" class="form-control" name="password" value="" id="password" placeholder="Password">
					  </div>
					</div>
					<div class="form-group">
					  <div class="col-lg-10 col-lg-offset-2">
							<button type="submit" value="login" class="btn btn-primary btn-default">Submit</button>
							<button type="reset" class="btn">Cancel</button>
					  </div>
					</div>
				</fieldset>
			</form>

          </div>
    
        </div>

      </div>
	  
	</div>
	
{% endblock %}

homework3/templates/upload.html
{% extends 'base.html' %}
{% block body %}

	<div class="container">
	
      <div class="page-header" id="banner">
        <div class="row">
			

			<div class="col-lg-7 col-md-6 col-sm-5">
	
			
			<!-- Upload form. Note enctype attribute! -->
			
			<form action"/upload/" method="post" enctype="multipart/form-data" class="form-horizontal" id="post-form">{% csrf_token %}
			  <fieldset>
				<legend>Create a new Job</legend>
				
				<div class="form-group">
				  <label for="jobname" class="col-lg-2 control-label">Job name</label>
				  <div class="col-lg-10">
					{{ form.non_field_errors }}{{form.name.errors }}
					<input type="text" class="form-control" id="id_name" name="name"  placeholder="Job name">
				  </div>
				</div>
		
				
				<div class="form-group">
				  <label for="textArea" class="col-lg-2 control-label">Mapper.py</label>
				  <div class="col-lg-10 ">{{ form.non_field_errors }}
					<p>{{form.file1.label_tag }}{{form.file1.help_text }}</p>
					<p>{{form.file1.errors }}{{form.file1 }}</p>
				  </div>
				</div>
				
				<div class="form-group">
				  <label for="textArea" class="col-lg-2 control-label">Reducer.py</label>
				  <div class="col-lg-10 ">
					<p>{{form.file2.label_tag }}{{form.file2.help_text }}</p>
					<p>{{form.file2.errors }}{{form.file2 }}</p>
				  </div>
				</div>
				
				<div class="form-group">
				  <label for="textArea" class="col-lg-2 control-label">Input file</label>
				  <div class="col-lg-10 ">
					<p>{{form.file3.label_tag }}{{form.file3.help_text }}</p>
					<p>{{form.file3.errors }}{{form.file3 }}</p>
				  </div>
				</div>
				
				
				<div class="form-group">
				  <div class="col-lg-10 col-lg-offset-2">
				  	<button type="submit" class="btn btn-default btn-primary" value="Post">Submit</button>
					<button type="reset" class="btn ">Cancel</button>
				  </div>
				</div>
				
			  </fieldset>
			</form>
			
			

		
			</div>
    
        </div>

      </div>
	  
	</div>

{% endblock %}

{% block scripts %}
{% load staticfiles %}
<script src="{% static 'js/upload.js' %}"></script>
{% endblock %}